import type { Product } from './types'

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Masala Khichdi',
    slug: 'masala-khichdi',
    description: 'Comfort in a bowl. A wholesome blend of rice, moong dal, and aromatic spices — just like ghar ka khana. Ready in 5 minutes flat.',
    price: 150,
    category: 'meals',
    image_url: '/products/masala-khichdi.jpg',
    weight: '150 gm',
    servings: 'Serves 2',
    prep_time: '5 mins',
    ingredients: 'Rice, Moong Dal, Turmeric, Cumin, Mustard Seeds, Curry Leaves, Green Chillies, Salt, Asafoetida',
    instructions: '1. Add the mix to 300ml boiling water\n2. Stir well and cover\n3. Cook on low flame for 5 minutes\n4. Serve hot with ghee and pickle',
    tags: ['comfort food', 'high protein', 'vegan', 'hero'],
    in_stock: true,
    is_featured: true,
    sort_order: 1,
    variants: [
      { weight: '150 gm', servings: 'Serves 2', price: 150 },
      { weight: '500 gm', servings: 'Serves 10', price: 400 },
    ],
  },
  {
    id: 'p2',
    name: 'Vanilla Cake',
    slug: 'vanilla-cake',
    description: 'Eggless, light, and absolutely delicious. Made with premium vanilla and pure ingredients. A perfect treat for tea time or celebrations.',
    price: 150,
    category: 'sweet',
    image_url: '/products/vanilla-cake.jpg',
    weight: '200 gm',
    servings: 'Serves 5',
    prep_time: '15 mins',
    ingredients: 'Wheat Flour, Sugar, Baking Powder, Vanilla Essence, Milk Powder, Salt',
    instructions: '1. Mix 200ml milk + 3 tbsp oil with the cake mix\n2. Whisk until smooth\n3. Pour into greased pan\n4. Bake at 180°C for 25 mins or microwave for 5 mins',
    tags: ['eggless', 'sweet', 'no preservatives'],
    in_stock: true,
    is_featured: true,
    sort_order: 2,
  },
  {
    id: 'p3',
    name: 'Moong Chilla',
    slug: 'moong-chilla',
    description: 'Crispy, protein-rich crepe made with moong dal. A healthy breakfast that takes just 4 minutes to make. Perfect for fitness-conscious eaters.',
    price: 150,
    category: 'breakfast',
    image_url: '/products/moong-chila.jpg',
    weight: '150 gm',
    servings: 'Makes 8',
    prep_time: '4 mins',
    ingredients: 'Moong Dal Flour, Rice Flour, Cumin, Green Chilli, Coriander, Salt, Turmeric',
    instructions: '1. Mix the powder with water to make a batter\n2. Heat a non-stick pan\n3. Spread thin and cook both sides\n4. Serve with green chutney',
    tags: ['healthy', 'high protein', 'breakfast'],
    in_stock: true,
    is_featured: true,
    sort_order: 3,
    variants: [
      { weight: '150 gm', servings: 'Makes 8', price: 150 },
      { weight: '500 gm', servings: 'Makes 24', price: 400 },
    ],
  },
  {
    id: 'p4',
    name: 'Shev Bhaji',
    slug: 'shev-bhaji',
    description: 'A bold Maharashtrian classic. Spicy tomato-onion gravy topped with crispy sev. Pairs perfectly with pav or roti.',
    price: 200,
    category: 'meals',
    image_url: '/products/shev-bhaji.jpg',
    weight: '150 gm',
    servings: 'Serves 5',
    prep_time: '5 mins',
    ingredients: 'Besan Sev, Onion Powder, Tomato Powder, Red Chilli, Garam Masala, Turmeric, Oil, Salt',
    instructions: '1. Add 200ml water to the mix and stir\n2. Cook on medium flame for 5 minutes\n3. Top with fresh sev\n4. Serve hot with pav or roti',
    tags: ['maharashtrian', 'spicy', 'quick'],
    in_stock: true,
    is_featured: false,
    sort_order: 4,
  },
  {
    id: 'p5',
    name: 'Matki Misal',
    slug: 'matki-misal',
    description: 'The quintessential Kolhapuri street food. Sprouted moth bean curry with a fiery kick. Top with farsan and enjoy!',
    price: 200,
    category: 'meals',
    image_url: '/products/matki-misal.jpg',
    weight: '250 gm',
    servings: 'Serves 4',
    prep_time: '5 mins',
    ingredients: 'Sprouted Matki, Red Chilli, Coconut, Garam Masala, Onion, Ginger, Garlic, Jaggery, Salt',
    instructions: '1. Add the mix to 400ml boiling water\n2. Stir and cook for 5 minutes\n3. Top with farsan, onion, and lemon\n4. Serve with pav',
    tags: ['maharashtrian', 'spicy', 'street food'],
    in_stock: true,
    is_featured: false,
    sort_order: 5,
  },
  {
    id: 'p6',
    name: 'Poha',
    slug: 'poha',
    description: 'Flattened rice with peanuts, curry leaves, and mild spices. A light, tasty breakfast favorite — especially for students!',
    price: 80,
    category: 'breakfast',
    image_url: '/products/instant-poha.jpg',
    weight: '150 gm',
    servings: 'Serves 2',
    prep_time: '5 mins',
    ingredients: 'Flattened Rice (Poha), Peanuts, Mustard Seeds, Curry Leaves, Turmeric, Green Chilli, Salt, Sugar',
    instructions: '1. Wash poha under running water\n2. Heat oil, add the spice sachet\n3. Mix in poha and cook for 2 minutes\n4. Garnish with coriander and lemon',
    tags: ['quick', 'light', 'traditional'],
    in_stock: true,
    is_featured: false,
    sort_order: 6,
    variants: [
      { weight: '150 gm', servings: 'Serves 2', price: 80 },
      { weight: '500 gm', servings: 'Serves 8', price: 300 },
    ],
  },
  {
    id: 'p7',
    name: 'Upma',
    slug: 'upma',
    description: 'Semolina with roasted vegetables and aromatic South Indian spices. A savory, satisfying breakfast in just 5 minutes.',
    price: 120,
    category: 'breakfast',
    image_url: '/products/rawa-upma.jpg',
    weight: '150 gm',
    servings: 'Serves 3',
    prep_time: '5 mins',
    ingredients: 'Semolina (Rava), Mustard Seeds, Curry Leaves, Onion, Green Chilli, Cashews, Salt',
    instructions: '1. Boil 300ml water\n2. Add the mix while stirring\n3. Cook covered on low flame for 3 minutes\n4. Serve hot with coconut chutney',
    tags: ['south indian', 'breakfast', 'healthy'],
    in_stock: true,
    is_featured: false,
    sort_order: 7,
    variants: [
      { weight: '150 gm', servings: 'Serves 3', price: 120 },
      { weight: '500 gm', servings: 'Serves 10', price: 350 },
    ],
  },
  {
    id: 'p8',
    name: 'Multigrain Dosa',
    slug: 'multigrain-dosa',
    description: 'A healthier twist on the classic dosa. Made with a blend of nutrient-rich grains for a crispy, guilt-free breakfast.',
    price: 150,
    category: 'breakfast',
    image_url: '/products/multigrain-dosa.jpg',
    weight: '150 gm',
    servings: 'Makes 8',
    prep_time: '5 mins',
    ingredients: 'Rice Flour, Urad Dal, Jowar, Bajra, Ragi, Fenugreek Seeds, Salt',
    instructions: '1. Mix the powder with water to make a thin batter\n2. Heat a non-stick pan\n3. Pour batter thick or thin as you like\n4. Cook until crispy golden on both sides',
    tags: ['healthy', 'multigrain', 'breakfast'],
    in_stock: true,
    is_featured: false,
    sort_order: 8,
    variants: [
      { weight: '150 gm', servings: 'Makes 8', price: 150 },
      { weight: '500 gm', servings: 'Makes 24', price: 400 },
    ],
  },
  {
    id: 'p9',
    name: 'Eggless Pancake',
    slug: 'eggless-pancake',
    description: 'Fluffy, golden pancakes without eggs. Perfect for a sweet morning start. Kids love it! Makes 12 mini pancakes.',
    price: 150,
    category: 'breakfast',
    image_url: '/products/eggless-pancake.jpg',
    weight: '150 gm',
    servings: 'Makes 12',
    prep_time: '4 mins',
    ingredients: 'Wheat Flour, Sugar, Baking Powder, Milk Powder, Vanilla, Salt',
    instructions: '1. Mix with 200ml milk or water\n2. Heat a pan with butter\n3. Pour small rounds and flip when bubbly\n4. Serve with honey, maple syrup, or fruits',
    tags: ['eggless', 'sweet', 'kids favorite'],
    in_stock: true,
    is_featured: false,
    sort_order: 9,
    variants: [
      { weight: '150 gm', servings: 'Makes 12', price: 150 },
      { weight: '500 gm', servings: 'Makes 28', price: 450 },
    ],
  },
  {
    id: 'p10',
    name: 'Oats Khichdi',
    slug: 'oats-khichdi',
    description: 'A healthy, fiber-rich spin on the classic khichdi. Made with oats and traditional spices for a nutritious comfort meal.',
    price: 150,
    category: 'meals',
    image_url: '/products/oats-khichdi.jpg',
    weight: '150 gm',
    servings: 'Serves 3',
    prep_time: '10 mins',
    ingredients: 'Oats, Moong Dal, Turmeric, Cumin, Mustard Seeds, Vegetables, Salt',
    instructions: '1. Add the mix to 400ml boiling water\n2. Stir well and cover\n3. Cook on low for 10 minutes\n4. Serve hot with a dollop of ghee',
    tags: ['healthy', 'high fiber', 'comfort food'],
    in_stock: true,
    is_featured: false,
    sort_order: 10,
    variants: [
      { weight: '150 gm', servings: 'Serves 3', price: 150 },
      { weight: '500 gm', servings: 'Serves 10', price: 400 },
    ],
  },
  {
    id: 'p11',
    name: 'Khandeshi Pithla',
    slug: 'khandeshi-pithla',
    description: 'A rustic Khandeshi delicacy. Spiced gram flour curry that pairs beautifully with bhakri or rice. Ready in just 4 minutes.',
    price: 80,
    category: 'meals',
    image_url: '/products/khandeshi-pithla.jpg',
    weight: '50 gm',
    servings: 'Serves 3',
    prep_time: '4 mins',
    ingredients: 'Besan (Gram Flour), Onion, Green Chilli, Garlic, Turmeric, Mustard Seeds, Curry Leaves, Salt',
    instructions: '1. Mix the powder with 200ml water\n2. Cook on medium flame while stirring\n3. Let it thicken for 3-4 minutes\n4. Serve with bhakri or rice',
    tags: ['khandeshi', 'traditional', 'quick'],
    in_stock: true,
    is_featured: false,
    sort_order: 11,
    variants: [
      { weight: '50 gm', servings: 'Serves 3', price: 80 },
      { weight: '150 gm', servings: 'Serves 9', price: 200 },
    ],
  },
  {
    id: 'p12',
    name: 'Rice Dhokla',
    slug: 'rice-dhokla',
    description: 'Soft, spongy rice-based dhokla. A Gujarati classic that makes for a perfect snack or light meal. Makes 30 pieces!',
    price: 150,
    category: 'meals',
    image_url: '/products/rice-dhokla.jpg',
    weight: '150 gm',
    servings: 'Makes 30',
    prep_time: '10 mins',
    ingredients: 'Rice Flour, Citric Acid, Eno Fruit Salt, Sugar, Mustard Seeds, Curry Leaves, Green Chilli',
    instructions: '1. Mix with water and Eno, stir quickly\n2. Pour into greased plate\n3. Steam for 10 minutes\n4. Temper with mustard seeds, serve with chutney',
    tags: ['gujarati', 'snack', 'steamed'],
    in_stock: true,
    is_featured: false,
    sort_order: 12,
  },
  {
    id: 'p13',
    name: 'Chocolate Cake',
    slug: 'chocolate-cake',
    description: 'Rich, moist chocolate cake — completely eggless. Made with real cocoa powder. The ultimate indulgence, guilt-free.',
    price: 150,
    category: 'sweet',
    image_url: '/products/chocolate-cake.jpg',
    weight: '200 gm',
    servings: 'Serves 5',
    prep_time: '15 mins',
    ingredients: 'Wheat Flour, Cocoa Powder, Sugar, Baking Powder, Milk Powder, Vanilla, Salt',
    instructions: '1. Mix 200ml milk + 3 tbsp oil with the cake mix\n2. Whisk until smooth\n3. Pour into greased pan\n4. Bake at 180°C for 25 mins or microwave for 5 mins',
    tags: ['eggless', 'chocolate', 'sweet'],
    in_stock: true,
    is_featured: false,
    sort_order: 13,
  },
  {
    id: 'p14',
    name: 'Kashmiri Kahwa',
    slug: 'kashmiri-kahwa',
    description: 'A royal Kashmiri green tea infused with saffron, cardamom, cinnamon, and almonds. One sip, and you\'re in the Valley.',
    price: 250,
    category: 'beverage',
    image_url: '/products/kashmiri-kahwa.jpg',
    weight: '150 gm',
    servings: 'Serves 20',
    prep_time: '1 min',
    ingredients: 'Green Tea, Saffron, Cinnamon, Cardamom, Almonds, Cloves, Rose Petals',
    instructions: '1. Boil one cup of water\n2. Add 1 tsp Kahwa mix\n3. Steep for 1-2 minutes\n4. Strain and serve (add honey if desired)',
    tags: ['beverage', 'kashmiri', 'aromatic'],
    in_stock: true,
    is_featured: false,
    sort_order: 14,
  },
  {
    id: 'p15',
    name: 'Green Chutney',
    slug: 'green-chutney',
    description: 'Fresh, tangy, and spicy. Our dried green chutney mix brings instant flavor to any snack. Just add water and it\'s ready!',
    price: 100,
    category: 'condiment',
    image_url: '/products/green-chutney.jpg',
    weight: '50 gm',
    servings: 'Serves 8',
    prep_time: '1 min',
    ingredients: 'Coriander, Mint, Green Chilli, Garlic, Cumin, Lemon, Salt, Sugar',
    instructions: '1. Add 2 tbsp of mix to 3 tbsp water\n2. Stir well\n3. Adjust water for thickness\n4. Serve with any snack!',
    tags: ['condiment', 'spicy', 'instant'],
    in_stock: true,
    is_featured: false,
    sort_order: 15,
  },
  {
    id: 'p16',
    name: 'Red Gravy',
    slug: 'red-gravy',
    description: 'A versatile base for any curry. Rich tomato-onion masala that turns any vegetable into a restaurant-style dish in minutes.',
    price: 150,
    category: 'condiment',
    image_url: '/products/red-gravy.jpg',
    weight: '50 gm',
    servings: 'Serves 4',
    prep_time: '5 mins',
    ingredients: 'Tomato Powder, Onion Powder, Red Chilli, Garam Masala, Kashmiri Chilli, Ginger, Garlic, Salt',
    instructions: '1. Add the mix to 200ml water\n2. Cook for 5 minutes on medium flame\n3. Add cooked vegetables or paneer\n4. Serve hot with roti or rice',
    tags: ['base gravy', 'versatile', 'restaurant style'],
    in_stock: true,
    is_featured: false,
    sort_order: 16,
    variants: [
      { weight: '50 gm', servings: 'Serves 4', price: 150 },
      { weight: '150 gm', servings: 'Serves 12', price: 300 },
    ],
  },
  {
    id: 'p17',
    name: 'Coconut Coffee',
    slug: 'coconut-coffee',
    description: 'A unique tropical twist on your daily brew. Premium coffee blended with coconut for a creamy, aromatic cup that energizes your day.',
    price: 250,
    category: 'beverage',
    image_url: '/products/coconut-coffee.jpg',
    weight: '150 gm',
    servings: 'Serves 15',
    prep_time: '2 mins',
    ingredients: 'Coffee Powder, Coconut Powder, Sugar, Cardamom',
    instructions: '1. Add 2 tsp of mix to a cup\n2. Pour hot water or milk\n3. Stir well\n4. Enjoy hot or iced',
    tags: ['beverage', 'coffee', 'coconut'],
    in_stock: true,
    is_featured: false,
    sort_order: 17,
  },
  {
    id: 'p18',
    name: 'Trail Mix',
    slug: 'trail-mix',
    description: 'A power-packed blend of nuts, seeds, and dried fruits. The perfect healthy snack for on-the-go energy and nutrition.',
    price: 250,
    category: 'snack',
    image_url: '/products/trail-mix.jpg',
    weight: '150 gm',
    servings: 'Serves 5',
    prep_time: 'Ready to eat',
    ingredients: 'Almonds, Cashews, Raisins, Pumpkin Seeds, Sunflower Seeds, Dried Cranberries',
    instructions: '1. Open the pack\n2. Grab a handful\n3. Enjoy anytime, anywhere!',
    tags: ['healthy', 'snack', 'nuts', 'energy'],
    in_stock: true,
    is_featured: false,
    sort_order: 18,
  },
  {
    id: 'p19',
    name: 'Dal Makhni',
    slug: 'dal-makhni',
    description: 'Rich, creamy, buttery dal — a North Indian restaurant classic. Slow-cooked flavor in just 5 minutes at home.',
    price: 200,
    category: 'meals',
    image_url: '/products/dal-makhni.jpg',
    weight: '150 gm',
    servings: 'Serves 4',
    prep_time: '5 mins',
    ingredients: 'Black Urad Dal, Rajma, Tomato, Butter, Cream, Garam Masala, Kasuri Methi, Salt',
    instructions: '1. Add the mix to 300ml boiling water\n2. Stir well and cook for 5 minutes\n3. Add a knob of butter for extra richness\n4. Serve hot with naan or rice',
    tags: ['north indian', 'creamy', 'comfort food'],
    in_stock: true,
    is_featured: false,
    sort_order: 19,
  },
  {
    id: 'p20',
    name: 'Cheesy Pasta',
    slug: 'cheesy-pasta',
    description: 'Creamy, cheesy pasta that kids and adults both love. Restaurant-style mac & cheese experience at home in minutes.',
    price: 200,
    category: 'meals',
    image_url: '/products/cheesy-pasta.jpg',
    weight: '160 gm',
    servings: 'Serves 2',
    prep_time: '8 mins',
    ingredients: 'Pasta, Cheese Powder, Milk Powder, Corn Starch, Herbs, Salt, Pepper',
    instructions: '1. Boil the pasta in water for 6 minutes\n2. Drain and return to pan\n3. Add the cheese sachet with 50ml milk\n4. Stir until creamy and serve hot',
    tags: ['cheesy', 'kids favorite', 'quick'],
    in_stock: true,
    is_featured: false,
    sort_order: 20,
  },
  {
    id: 'p21',
    name: 'Vermicelli Upma',
    slug: 'vermicelli-upma',
    description: 'Light and flavorful roasted vermicelli with vegetables and aromatic spices. A quick, satisfying meal anytime.',
    price: 200,
    category: 'breakfast',
    image_url: '/products/vermicelli-upma.jpg',
    weight: '150 gm',
    servings: 'Serves 2',
    prep_time: '5 mins',
    ingredients: 'Roasted Vermicelli, Mustard Seeds, Curry Leaves, Peanuts, Green Chilli, Turmeric, Salt',
    instructions: '1. Heat oil and add the spice sachet\n2. Add 300ml water and bring to boil\n3. Add vermicelli, stir and cover\n4. Cook on low for 3-4 minutes, serve hot',
    tags: ['quick', 'light', 'breakfast'],
    in_stock: true,
    is_featured: false,
    sort_order: 21,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return products
  return products.filter(p => p.category === category)
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.is_featured)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return products.filter(
    p =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some(t => t.toLowerCase().includes(q)) ||
      p.category.toLowerCase().includes(q)
  )
}
